/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organizations: Organization;
    memberships: Membership;
    invites: Invite;
    media: Media;
    'audit-logs': AuditLog;
    'feature-flags': FeatureFlag;
    'billing-customers': BillingCustomer;
    'backup-snapshots': BackupSnapshot;
    'billing-subscriptions': BillingSubscription;
    'billing-events': BillingEvent;
    'support-notes': SupportNote;
    'operational-events': OperationalEvent;
    'console-customers': ConsoleCustomer;
    'console-workspaces': ConsoleWorkspace;
    'console-events': ConsoleEvent;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    invites: InvitesSelect<false> | InvitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'feature-flags': FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
    'billing-customers': BillingCustomersSelect<false> | BillingCustomersSelect<true>;
    'backup-snapshots': BackupSnapshotsSelect<false> | BackupSnapshotsSelect<true>;
    'billing-subscriptions': BillingSubscriptionsSelect<false> | BillingSubscriptionsSelect<true>;
    'billing-events': BillingEventsSelect<false> | BillingEventsSelect<true>;
    'support-notes': SupportNotesSelect<false> | SupportNotesSelect<true>;
    'operational-events': OperationalEventsSelect<false> | OperationalEventsSelect<true>;
    'console-customers': ConsoleCustomersSelect<false> | ConsoleCustomersSelect<true>;
    'console-workspaces': ConsoleWorkspacesSelect<false> | ConsoleWorkspacesSelect<true>;
    'console-events': ConsoleEventsSelect<false> | ConsoleEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'app-settings': AppSetting;
    'ops-settings': OpsSetting;
    'legal-texts': LegalText;
    'billing-settings': BillingSetting;
    'email-templates': EmailTemplate;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'app-settings': AppSettingsSelect<false> | AppSettingsSelect<true>;
    'ops-settings': OpsSettingsSelect<false> | OpsSettingsSelect<true>;
    'legal-texts': LegalTextsSelect<false> | LegalTextsSelect<true>;
    'billing-settings': BillingSettingsSelect<false> | BillingSettingsSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'deliver-email': TaskDeliverEmail;
      'retry-billing-event': TaskRetryBillingEvent;
      'sync-organization-billing': TaskSyncOrganizationBilling;
      'export-organization-snapshot': TaskExportOrganizationSnapshot;
      'ai-post-process': TaskAiPostProcess;
      'run-maintenance': TaskRunMaintenance;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      'nightly-maintenance': WorkflowNightlyMaintenance;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  organizations?:
    | {
        organization: number | Organization;
        role?: ('org_owner' | 'org_admin' | 'manager' | 'editor' | 'member' | 'viewer') | null;
        status?: ('invited' | 'active' | 'suspended') | null;
        joinedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  currentOrganization?: (number | null) | Organization;
  platformRole?:
    | (
        | 'platform_owner'
        | 'platform_admin'
        | 'platform_operator'
        | 'platform_support'
        | 'platform_billing'
        | 'platform_readonly'
      )
    | null;
  timezone?: string | null;
  locale?: string | null;
  status?: ('active' | 'invited' | 'disabled' | 'locked' | 'suspended') | null;
  lastLoginAt?: string | null;
  security?: {
    passwordChangedAt?: string | null;
    mfa?: {
      enabled?: boolean | null;
      preferredMethod?: ('totp' | 'webauthn' | 'email') | null;
      enrolledAt?: string | null;
      verifiedAt?: string | null;
      recoveryCodeVersion?: number | null;
      secret?: string | null;
      pendingSecret?: string | null;
      recoveryCodeHashes?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
  };
  notificationSettings?: {
    billing?: {
      email?: boolean | null;
      inApp?: boolean | null;
    };
    product?: {
      email?: boolean | null;
      inApp?: boolean | null;
    };
    security?: {
      email?: boolean | null;
      inApp?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  slug: string;
  type?: ('workspace' | 'client' | 'internal') | null;
  status?: ('active' | 'paused' | 'archived') | null;
  ownerUser?: (number | null) | User;
  planKey?: string | null;
  billingStatus?: ('none' | 'trialing' | 'active' | 'grace' | 'past_due' | 'unpaid' | 'canceled' | 'incomplete') | null;
  gracePeriodEndsAt?: string | null;
  archivedAt?: string | null;
  archivedBy?: (number | null) | User;
  seatLimit?: number | null;
  billingEntitlements?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notificationDefaults?: {
    billing?: {
      email?: boolean | null;
      inApp?: boolean | null;
    };
    product?: {
      email?: boolean | null;
      inApp?: boolean | null;
    };
    security?: {
      email?: boolean | null;
      inApp?: boolean | null;
    };
  };
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  organization?: (number | null) | Organization;
  user: number | User;
  role?: ('org_owner' | 'org_admin' | 'manager' | 'editor' | 'member' | 'viewer') | null;
  status?: ('invited' | 'active' | 'suspended') | null;
  invitedBy?: (number | null) | User;
  joinedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invites".
 */
export interface Invite {
  id: number;
  organization?: (number | null) | Organization;
  email: string;
  role?: ('org_owner' | 'org_admin' | 'manager' | 'editor' | 'member' | 'viewer') | null;
  status?: ('pending' | 'accepted' | 'revoked' | 'expired') | null;
  tokenHash: string;
  expiresAt: string;
  invitedBy?: (number | null) | User;
  acceptedBy?: (number | null) | User;
  acceptedAt?: string | null;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  organization?: (number | null) | Organization;
  visibility?: ('private' | 'public') | null;
  objectKey?: string | null;
  deliveryUrl?: string | null;
  tags?: string[] | null;
  purpose?: ('asset' | 'export' | 'backup') | null;
  retentionState?: ('active' | 'scheduled_for_purge' | 'purged') | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  retentionUntil?: string | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  organization?: (number | null) | Organization;
  targetType?: string | null;
  targetId?: string | null;
  action: string;
  result?: ('success' | 'failure' | 'denied') | null;
  actorUser?: (number | null) | User;
  actorType?: string | null;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason?: string | null;
  ip?: string | null;
  requestId?: string | null;
  requestMethod?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags".
 */
export interface FeatureFlag {
  id: number;
  key: string;
  scopeType?: ('platform' | 'environment' | 'organization' | 'user') | null;
  scopeId?: string | null;
  environment?: ('development' | 'staging' | 'production') | null;
  enabled?: boolean | null;
  rolloutPercent?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  rulesJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-customers".
 */
export interface BillingCustomer {
  id: number;
  organization?: (number | null) | Organization;
  stripeCustomerId: string;
  email?: string | null;
  currency?: string | null;
  taxStatus?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-snapshots".
 */
export interface BackupSnapshot {
  id: number;
  snapshotType?: ('full_environment' | 'database' | 'object_storage' | 'tenant' | 'restore_drill') | null;
  scopeType?: ('platform' | 'organization' | 'project') | null;
  scopeId?: string | null;
  status?: ('available' | 'failed' | 'expired') | null;
  snapshotAt: string;
  retentionUntil?: string | null;
  artifactUri?: string | null;
  storageKey?: string | null;
  checksum?: string | null;
  sizeBytes?: number | null;
  reason?: string | null;
  summary: string;
  notes?: string | null;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recordedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-subscriptions".
 */
export interface BillingSubscription {
  id: number;
  organization?: (number | null) | Organization;
  billingCustomer?: (number | null) | BillingCustomer;
  planKey: string;
  stripeSubscriptionId: string;
  stripeProductId?: string | null;
  stripePriceIds?: string[] | null;
  status: string;
  quantity?: number | null;
  seatLimit?: number | null;
  seatsInUse?: number | null;
  gracePeriodEndsAt?: string | null;
  entitlementsJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  usageStateJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  cancelAtPeriodEnd?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-events".
 */
export interface BillingEvent {
  id: number;
  organization?: (number | null) | Organization;
  source?: ('stripe' | 'meter') | null;
  stripeEventId?: string | null;
  eventType: string;
  status?: ('pending' | 'processed' | 'failed' | 'queued') | null;
  retryCount?: number | null;
  processedAt?: string | null;
  idempotencyKey?: string | null;
  meterKey?: string | null;
  quantity?: number | null;
  requestId?: string | null;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-notes".
 */
export interface SupportNote {
  id: number;
  organization?: (number | null) | Organization;
  createdBy?: (number | null) | User;
  visibility?: ('ops' | 'billing' | 'support') | null;
  body: string;
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-events".
 */
export interface OperationalEvent {
  id: number;
  organization?: (number | null) | Organization;
  eventType?:
    | (
        | 'job_failure'
        | 'webhook_failure'
        | 'backup_snapshot'
        | 'media_restore'
        | 'restore_drill'
        | 'maintenance_action'
        | 'bootstrap_manifest'
      )
    | null;
  status?: ('pending' | 'succeeded' | 'failed' | 'acknowledged') | null;
  queueName?: string | null;
  summary: string;
  relatedCollection?: string | null;
  relatedId?: string | null;
  retryCount?: number | null;
  reason?: string | null;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  acknowledgedAt?: string | null;
  acknowledgedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-customers".
 */
export interface ConsoleCustomer {
  id: number;
  organization: number | Organization;
  title: string;
  status?: ('draft' | 'active' | 'archived') | null;
  accountTier?: ('starter' | 'growth' | 'scale' | 'enterprise') | null;
  ownerName?: string | null;
  ownerEmail?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-workspaces".
 */
export interface ConsoleWorkspace {
  id: number;
  organization: number | Organization;
  customer: number | ConsoleCustomer;
  title: string;
  status?: ('draft' | 'active' | 'archived') | null;
  workspaceType?: ('client' | 'internal' | 'pilot' | 'production') | null;
  lastActivityAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-events".
 */
export interface ConsoleEvent {
  id: number;
  organization: number | Organization;
  customer?: (number | null) | ConsoleCustomer;
  workspace?: (number | null) | ConsoleWorkspace;
  title: string;
  status?: ('draft' | 'active' | 'archived') | null;
  eventType?: ('note' | 'kickoff' | 'request' | 'delivery' | 'billing' | 'incident') | null;
  severity?: ('low' | 'medium' | 'high') | null;
  occurredAt?: string | null;
  details?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'deliver-email'
          | 'retry-billing-event'
          | 'sync-organization-billing'
          | 'export-organization-snapshot'
          | 'ai-post-process'
          | 'run-maintenance'
          | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'nightly-maintenance' | null;
  taskSlug?:
    | (
        | 'inline'
        | 'deliver-email'
        | 'retry-billing-event'
        | 'sync-organization-billing'
        | 'export-organization-snapshot'
        | 'ai-post-process'
        | 'run-maintenance'
        | 'schedulePublish'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'invites';
        value: number | Invite;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'feature-flags';
        value: number | FeatureFlag;
      } | null)
    | ({
        relationTo: 'billing-customers';
        value: number | BillingCustomer;
      } | null)
    | ({
        relationTo: 'backup-snapshots';
        value: number | BackupSnapshot;
      } | null)
    | ({
        relationTo: 'billing-subscriptions';
        value: number | BillingSubscription;
      } | null)
    | ({
        relationTo: 'billing-events';
        value: number | BillingEvent;
      } | null)
    | ({
        relationTo: 'support-notes';
        value: number | SupportNote;
      } | null)
    | ({
        relationTo: 'operational-events';
        value: number | OperationalEvent;
      } | null)
    | ({
        relationTo: 'console-customers';
        value: number | ConsoleCustomer;
      } | null)
    | ({
        relationTo: 'console-workspaces';
        value: number | ConsoleWorkspace;
      } | null)
    | ({
        relationTo: 'console-events';
        value: number | ConsoleEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  organizations?:
    | T
    | {
        organization?: T;
        role?: T;
        status?: T;
        joinedAt?: T;
        id?: T;
      };
  currentOrganization?: T;
  platformRole?: T;
  timezone?: T;
  locale?: T;
  status?: T;
  lastLoginAt?: T;
  security?:
    | T
    | {
        passwordChangedAt?: T;
        mfa?:
          | T
          | {
              enabled?: T;
              preferredMethod?: T;
              enrolledAt?: T;
              verifiedAt?: T;
              recoveryCodeVersion?: T;
              secret?: T;
              pendingSecret?: T;
              recoveryCodeHashes?: T;
            };
      };
  notificationSettings?:
    | T
    | {
        billing?:
          | T
          | {
              email?: T;
              inApp?: T;
            };
        product?:
          | T
          | {
              email?: T;
              inApp?: T;
            };
        security?:
          | T
          | {
              email?: T;
              inApp?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  status?: T;
  ownerUser?: T;
  planKey?: T;
  billingStatus?: T;
  gracePeriodEndsAt?: T;
  archivedAt?: T;
  archivedBy?: T;
  seatLimit?: T;
  billingEntitlements?: T;
  notificationDefaults?:
    | T
    | {
        billing?:
          | T
          | {
              email?: T;
              inApp?: T;
            };
        product?:
          | T
          | {
              email?: T;
              inApp?: T;
            };
        security?:
          | T
          | {
              email?: T;
              inApp?: T;
            };
      };
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  organization?: T;
  user?: T;
  role?: T;
  status?: T;
  invitedBy?: T;
  joinedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invites_select".
 */
export interface InvitesSelect<T extends boolean = true> {
  organization?: T;
  email?: T;
  role?: T;
  status?: T;
  tokenHash?: T;
  expiresAt?: T;
  invitedBy?: T;
  acceptedBy?: T;
  acceptedAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  organization?: T;
  visibility?: T;
  objectKey?: T;
  deliveryUrl?: T;
  tags?: T;
  purpose?: T;
  retentionState?: T;
  deletedAt?: T;
  deletedBy?: T;
  retentionUntil?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  organization?: T;
  targetType?: T;
  targetId?: T;
  action?: T;
  result?: T;
  actorUser?: T;
  actorType?: T;
  detail?: T;
  reason?: T;
  ip?: T;
  requestId?: T;
  requestMethod?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  key?: T;
  scopeType?: T;
  scopeId?: T;
  environment?: T;
  enabled?: T;
  rolloutPercent?: T;
  startsAt?: T;
  endsAt?: T;
  rulesJson?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-customers_select".
 */
export interface BillingCustomersSelect<T extends boolean = true> {
  organization?: T;
  stripeCustomerId?: T;
  email?: T;
  currency?: T;
  taxStatus?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-snapshots_select".
 */
export interface BackupSnapshotsSelect<T extends boolean = true> {
  snapshotType?: T;
  scopeType?: T;
  scopeId?: T;
  status?: T;
  snapshotAt?: T;
  retentionUntil?: T;
  artifactUri?: T;
  storageKey?: T;
  checksum?: T;
  sizeBytes?: T;
  reason?: T;
  summary?: T;
  notes?: T;
  detail?: T;
  recordedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-subscriptions_select".
 */
export interface BillingSubscriptionsSelect<T extends boolean = true> {
  organization?: T;
  billingCustomer?: T;
  planKey?: T;
  stripeSubscriptionId?: T;
  stripeProductId?: T;
  stripePriceIds?: T;
  status?: T;
  quantity?: T;
  seatLimit?: T;
  seatsInUse?: T;
  gracePeriodEndsAt?: T;
  entitlementsJson?: T;
  usageStateJson?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  cancelAtPeriodEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-events_select".
 */
export interface BillingEventsSelect<T extends boolean = true> {
  organization?: T;
  source?: T;
  stripeEventId?: T;
  eventType?: T;
  status?: T;
  retryCount?: T;
  processedAt?: T;
  idempotencyKey?: T;
  meterKey?: T;
  quantity?: T;
  requestId?: T;
  rawPayload?: T;
  errorJson?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-notes_select".
 */
export interface SupportNotesSelect<T extends boolean = true> {
  organization?: T;
  createdBy?: T;
  visibility?: T;
  body?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-events_select".
 */
export interface OperationalEventsSelect<T extends boolean = true> {
  organization?: T;
  eventType?: T;
  status?: T;
  queueName?: T;
  summary?: T;
  relatedCollection?: T;
  relatedId?: T;
  retryCount?: T;
  reason?: T;
  detail?: T;
  acknowledgedAt?: T;
  acknowledgedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-customers_select".
 */
export interface ConsoleCustomersSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  status?: T;
  accountTier?: T;
  ownerName?: T;
  ownerEmail?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-workspaces_select".
 */
export interface ConsoleWorkspacesSelect<T extends boolean = true> {
  organization?: T;
  customer?: T;
  title?: T;
  status?: T;
  workspaceType?: T;
  lastActivityAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "console-events_select".
 */
export interface ConsoleEventsSelect<T extends boolean = true> {
  organization?: T;
  customer?: T;
  workspace?: T;
  title?: T;
  status?: T;
  eventType?: T;
  severity?: T;
  occurredAt?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings".
 */
export interface AppSetting {
  id: number;
  appName: string;
  defaultLocale?: string | null;
  supportEmail?: string | null;
  supportDocsUrl?: string | null;
  statusBanner?: string | null;
  maintenanceMode?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-settings".
 */
export interface OpsSetting {
  id: number;
  incidentBanner?: string | null;
  dangerousActionsEnabled?: boolean | null;
  exportRetentionDays?: number | null;
  backupPolicyText?: string | null;
  restoreDrillInstructions?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-texts".
 */
export interface LegalText {
  id: number;
  termsVersion: string;
  termsBody: string;
  privacyVersion: string;
  privacyBody: string;
  consentVersion: string;
  consentBody: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-settings".
 */
export interface BillingSetting {
  id: number;
  stripeApiVersion: string;
  defaultCurrency: string;
  gracePeriodDays?: number | null;
  retryPolicy?: {
    maxAttempts?: number | null;
    backoffMs?: number | null;
  };
  plans?:
    | {
        planKey: string;
        label: string;
        stripeProductId?: string | null;
        stripePriceIds?: string[] | null;
        seatLimit?: number | null;
        meterKeys?: string[] | null;
        entitlementsJson?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  invite?: {
    subject?: string | null;
    body?: string | null;
  };
  resetPassword?: {
    subject?: string | null;
    body?: string | null;
  };
  billingFailed?: {
    subject?: string | null;
    body?: string | null;
  };
  welcome?: {
    subject?: string | null;
    body?: string | null;
  };
  genericNotice?: {
    subject?: string | null;
    body?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings_select".
 */
export interface AppSettingsSelect<T extends boolean = true> {
  appName?: T;
  defaultLocale?: T;
  supportEmail?: T;
  supportDocsUrl?: T;
  statusBanner?: T;
  maintenanceMode?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-settings_select".
 */
export interface OpsSettingsSelect<T extends boolean = true> {
  incidentBanner?: T;
  dangerousActionsEnabled?: T;
  exportRetentionDays?: T;
  backupPolicyText?: T;
  restoreDrillInstructions?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-texts_select".
 */
export interface LegalTextsSelect<T extends boolean = true> {
  termsVersion?: T;
  termsBody?: T;
  privacyVersion?: T;
  privacyBody?: T;
  consentVersion?: T;
  consentBody?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-settings_select".
 */
export interface BillingSettingsSelect<T extends boolean = true> {
  stripeApiVersion?: T;
  defaultCurrency?: T;
  gracePeriodDays?: T;
  retryPolicy?:
    | T
    | {
        maxAttempts?: T;
        backoffMs?: T;
      };
  plans?:
    | T
    | {
        planKey?: T;
        label?: T;
        stripeProductId?: T;
        stripePriceIds?: T;
        seatLimit?: T;
        meterKeys?: T;
        entitlementsJson?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  invite?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  resetPassword?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  billingFailed?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  welcome?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  genericNotice?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeliver-email".
 */
export interface TaskDeliverEmail {
  input: {
    templateKey: string;
    to: string;
  };
  output: {
    delivered: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRetry-billing-event".
 */
export interface TaskRetryBillingEvent {
  input: {
    billingEventId: string;
  };
  output: {
    retried: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSync-organization-billing".
 */
export interface TaskSyncOrganizationBilling {
  input: {
    organizationId: string;
  };
  output: {
    synced: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExport-organization-snapshot".
 */
export interface TaskExportOrganizationSnapshot {
  input: {
    organizationId?: string | null;
  };
  output: {
    exported: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAi-post-process".
 */
export interface TaskAiPostProcess {
  input: {
    artifactId?: string | null;
  };
  output: {
    processed: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRun-maintenance".
 */
export interface TaskRunMaintenance {
  input?: unknown;
  output: {
    backupRetention: number;
    mediaRetention: number;
    staleBillingEvents: number;
    restoreDrillReminder: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    global?: ('app-settings' | 'ops-settings' | 'legal-texts' | 'billing-settings' | 'email-templates') | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowNightly-maintenance".
 */
export interface WorkflowNightlyMaintenance {
  input?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}